### ISSUE TITLE
upside down lines under normal lines cause rider to become stuck.

### ISSUE THREAD

**Issue by Xeddius** [jealouscloud/linerider-advanced#52]
If you have an upside down line directly underneath a straight line at a sharp angle (like for the original line extension/floating trick) the rider becomes trapped. This also makes it difficult to make gravity hooks and a few useful tricks that still work on the original.

In the event the rider does not end up stuck the rider starts to fall through the line earlier than expected.
Current Behavior:
![Selection_022](https://user-images.githubusercontent.com/6382895/59528253-c6f4e200-8eab-11e9-96a0-1c7476507394.png)
Expected Behavior:
![Selection_021](https://user-images.githubusercontent.com/6382895/59528280-d5db9480-8eab-11e9-8387-5989a962164f.png)

**Comment by jealouscloud** [comment]
The physics for LRA and linerider.com are programmed to be identical to the original flash 6.2. However, as far as I am aware, linerider.com does not implement a feature in 6.2 called line extensions, specifically, creating them. This is what's involved when creating anti-gravity wells, the previously mentioned 'floating trick'. 

As for the reported bug, as long as the inverted line is below the 'forward' line, as well as the rider is going 'forward' on said line, you should run into issues. The physics behavior is locked into place due to 6.2 compatibility being a requirement. This should be identical on linerider.com, which you can test by saving a file and loading it between versions. But as it does not create line extensions for new angled lines, you may see some differences with lines at an angle between -0% and -180 degrees, which would put the second line above the 'forward' line.

If you can show a physics difference between linerider.com and LRA by having a TRK or .track.json file function differently between versions, I'd love to see that track file, however.

**Comment by Xeddius** [comment]
The 'floating trick' is present in the original flash version, I haven't been able to reproduce it on the Linerider.com website after the first time (Might just be a quirk or maybe it was patched.) But it was used often in the flash version. 
![Floating](https://user-images.githubusercontent.com/6382895/59983241-4e98ca00-95eb-11e9-9bad-67a8e88da54f.png)
![lines](https://user-images.githubusercontent.com/6382895/59983242-4e98ca00-95eb-11e9-8c3c-34cdd7c60ccf.png)

This is the typical behavior that Linerider 6.2 had.

**Comment by jealouscloud** [comment]
linerider.com neglects to implement the creation of line extensions which overall can lead to unexpected falling through lines. This is why the floating anti gravity well trick does not work on it. Your method pictured for creating an anti gravity well is actually too far angled >180 degrees. LRA uses the same general conditions 6.2 does to create a line extension. 
I will need steps to replicate this issue to proceed, or as far as I can tell there isn't one.

**Comment by Xeddius** [comment]
I thought that you might, well here's the thing, I can create the lines on 6.2 and they work but attempting to do the EXACT same thing in LRA fails every single time. However, importing from the 6.2 .sol save works.
[savedLines.sol.zip](https://github.com/jealouscloud/linerider-advanced/files/3318706/savedLines.sol.zip)
here is a working example.

**Comment by Xeddius** [comment]
Perhaps it's just something weird going on with my hardware/software. I'll keep studying this and when I have a better understanding of what is going on I'll report back.
